/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Francisco
 */
public class FrmDonacion extends javax.swing.JFrame {

    /**
     * Creates new form FrmDonacion
     */
    public FrmDonacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labNombre = new javax.swing.JLabel();
        labSexo = new javax.swing.JLabel();
        labFechaN = new javax.swing.JLabel();
        btnIngresarD = new javax.swing.JButton();
        displayFechaN = new javax.swing.JLabel();
        displayNombre = new javax.swing.JLabel();
        labBuscarRut = new javax.swing.JLabel();
        displaySexo = new javax.swing.JLabel();
        txtBuscarRut = new javax.swing.JTextField();
        btnModificarD = new javax.swing.JButton();
        labApellido = new javax.swing.JLabel();
        labCiudad = new javax.swing.JLabel();
        btnBuscarRut = new javax.swing.JButton();
        labTipoS = new javax.swing.JLabel();
        displayCiudad = new javax.swing.JLabel();
        displayTipoS = new javax.swing.JLabel();
        displayApellido = new javax.swing.JLabel();
        btnEliminarD = new javax.swing.JButton();
        cboxTipoDonacion = new javax.swing.JComboBox<>();
        cboxCentro = new javax.swing.JComboBox<>();
        labCentro = new javax.swing.JLabel();
        txtCodPaciente = new javax.swing.JTextField();
        labTipoD = new javax.swing.JLabel();
        labCodPaciente = new javax.swing.JLabel();
        labFechaD = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnBuscarCodigoD = new javax.swing.JButton();
        txtFechaD = new javax.swing.JTextField();
        labCodDonacion = new javax.swing.JLabel();
        txtCodDonacion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(555, 555));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ficha Ingreso de Donacion"));
        jPanel1.setMaximumSize(new java.awt.Dimension(327, 327));
        jPanel1.setPreferredSize(new java.awt.Dimension(562, 347));

        labNombre.setText("Nombre");

        labSexo.setText("Sexo");

        labFechaN.setText("Fecha Nac.");

        btnIngresarD.setText("Ingresar Donacion");
        btnIngresarD.setActionCommand("CMD_ENTERD");
        btnIngresarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarDActionPerformed(evt);
            }
        });

        displayFechaN.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        displayFechaN.setForeground(new java.awt.Color(0, 0, 153));
        displayFechaN.setText("-");

        displayNombre.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        displayNombre.setForeground(new java.awt.Color(0, 0, 153));
        displayNombre.setText("-");

        labBuscarRut.setText("Rut");

        displaySexo.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        displaySexo.setForeground(new java.awt.Color(0, 0, 153));
        displaySexo.setText("-");

        btnModificarD.setText("Modificar Donacion");
        btnModificarD.setActionCommand("CMD_MODD");
        btnModificarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarDActionPerformed(evt);
            }
        });

        labApellido.setText("Apellido");

        labCiudad.setText("Ciudad");

        btnBuscarRut.setText("Buscar");
        btnBuscarRut.setActionCommand("CMD_FINDR");

        labTipoS.setText("Tipo Sangre");

        displayCiudad.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        displayCiudad.setForeground(new java.awt.Color(0, 0, 153));
        displayCiudad.setText("-");

        displayTipoS.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        displayTipoS.setForeground(new java.awt.Color(0, 0, 153));
        displayTipoS.setText("-");

        displayApellido.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        displayApellido.setForeground(new java.awt.Color(0, 0, 153));
        displayApellido.setText("-");

        btnEliminarD.setText("Eliminar Donacion");
        btnEliminarD.setActionCommand("CMD_DELETED");
        btnEliminarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDActionPerformed(evt);
            }
        });

        cboxTipoDonacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALTRUISTA", "REPOSICION" }));
        cboxTipoDonacion.setSelectedIndex(1);
        cboxTipoDonacion.setActionCommand("CMD_TDBOX");
        cboxTipoDonacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cboxTipoDonacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxTipoDonacionActionPerformed(evt);
            }
        });

        cboxCentro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CONCEPCION", "TALCAHUANO", "CHIGUAYANTE" }));
        cboxCentro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labCentro.setText("Centro Donacion");

        labTipoD.setText("Tipo de Donacion");

        labCodPaciente.setText("Codigo Paciente");

        labFechaD.setText("Fecha Donacion");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.setActionCommand("CMD_CLEAR");

        btnBuscarCodigoD.setText("Buscar");
        btnBuscarCodigoD.setActionCommand("CMD_FINDD");
        btnBuscarCodigoD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCodigoDActionPerformed(evt);
            }
        });

        labCodDonacion.setText("Cod. Donacion");

        txtCodDonacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodDonacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnIngresarD, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificarD, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarD, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(displayNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(displaySexo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labFechaN, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(displayFechaN, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(labApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(71, 71, 71))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(labCodDonacion)
                                                .addGap(18, 18, 18)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtFechaD, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labBuscarRut)
                                            .addComponent(txtBuscarRut, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCodDonacion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(labCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(72, 72, 72)
                                        .addComponent(labFechaD, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(displayApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labTipoS, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(displayCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(displayTipoS, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboxCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboxTipoDonacion, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labCodPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labTipoD, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarRut, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCodigoD, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodDonacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labCodDonacion))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labBuscarRut)
                            .addComponent(labApellido)
                            .addComponent(labNombre))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(displayApellido)
                                    .addComponent(displayNombre)
                                    .addComponent(txtBuscarRut, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labTipoS)
                                    .addComponent(labSexo)
                                    .addComponent(labCentro))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(displayTipoS)
                                    .addComponent(displaySexo)
                                    .addComponent(cboxCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(labCiudad)
                                            .addComponent(labFechaN)
                                            .addComponent(labFechaD))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(displayCiudad)
                                            .addComponent(displayFechaN)))
                                    .addComponent(txtFechaD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnBuscarCodigoD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBuscarRut, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(labTipoD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboxTipoDonacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(labCodPaciente)
                                        .addGap(33, 33, 33))
                                    .addComponent(txtCodPaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresarD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarDActionPerformed

    private void btnBuscarCodigoDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCodigoDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarCodigoDActionPerformed

    private void txtCodDonacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodDonacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodDonacionActionPerformed

    private void btnModificarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarDActionPerformed

    private void btnEliminarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarDActionPerformed

    private void cboxTipoDonacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxTipoDonacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxTipoDonacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDonacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDonacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDonacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDonacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDonacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscarCodigoD;
    public javax.swing.JButton btnBuscarRut;
    public javax.swing.JButton btnEliminarD;
    public javax.swing.JButton btnIngresarD;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JButton btnModificarD;
    public javax.swing.JComboBox<String> cboxCentro;
    public javax.swing.JComboBox<String> cboxTipoDonacion;
    public javax.swing.JLabel displayApellido;
    public javax.swing.JLabel displayCiudad;
    public javax.swing.JLabel displayFechaN;
    public javax.swing.JLabel displayNombre;
    public javax.swing.JLabel displaySexo;
    public javax.swing.JLabel displayTipoS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labApellido;
    private javax.swing.JLabel labBuscarRut;
    private javax.swing.JLabel labCentro;
    private javax.swing.JLabel labCiudad;
    private javax.swing.JLabel labCodDonacion;
    private javax.swing.JLabel labCodPaciente;
    private javax.swing.JLabel labFechaD;
    private javax.swing.JLabel labFechaN;
    private javax.swing.JLabel labNombre;
    private javax.swing.JLabel labSexo;
    private javax.swing.JLabel labTipoD;
    private javax.swing.JLabel labTipoS;
    public javax.swing.JTextField txtBuscarRut;
    public javax.swing.JTextField txtCodDonacion;
    public javax.swing.JTextField txtCodPaciente;
    public javax.swing.JTextField txtFechaD;
    // End of variables declaration//GEN-END:variables
}
