/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Francisco
 */
public class FrmDonacion extends javax.swing.JFrame {

    /**
     * Creates new form FrmDonacion
     */
    public FrmDonacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnIngresarD = new javax.swing.JButton();
        labBuscarRut = new javax.swing.JLabel();
        txtBuscarRut = new javax.swing.JTextField();
        btnModificarD = new javax.swing.JButton();
        btnBuscarRut = new javax.swing.JButton();
        btnEliminarD = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnBuscarCodigoD = new javax.swing.JButton();
        labCodDonacion = new javax.swing.JLabel();
        txtCodDonacion = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        labNombre = new javax.swing.JLabel();
        displayCiudad = new javax.swing.JLabel();
        labApellido = new javax.swing.JLabel();
        labFechaN = new javax.swing.JLabel();
        displayApellido = new javax.swing.JLabel();
        labSexo = new javax.swing.JLabel();
        displayTipoS = new javax.swing.JLabel();
        displayFechaN = new javax.swing.JLabel();
        displaySexo = new javax.swing.JLabel();
        labTipoS = new javax.swing.JLabel();
        displayNombre = new javax.swing.JLabel();
        labCiudad = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        labTipoD = new javax.swing.JLabel();
        cboxCentro = new javax.swing.JComboBox<>();
        txtCodPaciente = new javax.swing.JTextField();
        cboxTipoDonacion = new javax.swing.JComboBox<>();
        txtFechaD = new javax.swing.JTextField();
        labCentro = new javax.swing.JLabel();
        labFechaD = new javax.swing.JLabel();
        labCodPaciente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setSize(new java.awt.Dimension(555, 555));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ficha Ingreso de Donacion"));
        jPanel1.setMaximumSize(new java.awt.Dimension(327, 327));
        jPanel1.setPreferredSize(new java.awt.Dimension(562, 347));

        btnIngresarD.setFont(new java.awt.Font("Trebuchet MS", 1, 10)); // NOI18N
        btnIngresarD.setText("Ingresar Donación");
        btnIngresarD.setActionCommand("CMD_ENTERD");
        btnIngresarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarDActionPerformed(evt);
            }
        });

        labBuscarRut.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        labBuscarRut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labBuscarRut.setText("Rut");

        btnModificarD.setFont(new java.awt.Font("Trebuchet MS", 1, 10)); // NOI18N
        btnModificarD.setText("Modificar Donación");
        btnModificarD.setActionCommand("CMD_MODD");
        btnModificarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarDActionPerformed(evt);
            }
        });

        btnBuscarRut.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        btnBuscarRut.setText("Buscar");
        btnBuscarRut.setActionCommand("CMD_FINDR");

        btnEliminarD.setFont(new java.awt.Font("Trebuchet MS", 1, 10)); // NOI18N
        btnEliminarD.setText("Eliminar Donación");
        btnEliminarD.setActionCommand("CMD_DELETED");
        btnEliminarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarDActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Trebuchet MS", 1, 10)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setActionCommand("CMD_CLEAR");

        btnBuscarCodigoD.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        btnBuscarCodigoD.setText("Buscar");
        btnBuscarCodigoD.setActionCommand("CMD_FINDD");
        btnBuscarCodigoD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCodigoDActionPerformed(evt);
            }
        });

        labCodDonacion.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        labCodDonacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labCodDonacion.setText("Código Donación");

        txtCodDonacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodDonacionActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        labNombre.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        labNombre.setText("Nombre");

        displayCiudad.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        displayCiudad.setForeground(new java.awt.Color(0, 0, 153));
        displayCiudad.setText("-");

        labApellido.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        labApellido.setText("Apellido");

        labFechaN.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        labFechaN.setText("Fecha de Nacimiento");

        displayApellido.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        displayApellido.setForeground(new java.awt.Color(0, 0, 153));
        displayApellido.setText("-");

        labSexo.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        labSexo.setText("Sexo");

        displayTipoS.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        displayTipoS.setForeground(new java.awt.Color(0, 0, 153));
        displayTipoS.setText("-");

        displayFechaN.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        displayFechaN.setForeground(new java.awt.Color(0, 0, 153));
        displayFechaN.setText("-");

        displaySexo.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        displaySexo.setForeground(new java.awt.Color(0, 0, 153));
        displaySexo.setText("-");

        labTipoS.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        labTipoS.setText("Tipo de Sangre");

        displayNombre.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        displayNombre.setForeground(new java.awt.Color(0, 0, 153));
        displayNombre.setText("-");

        labCiudad.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        labCiudad.setText("Ciudad");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labFechaN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(displayFechaN, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(displayTipoS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labTipoS, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(displayNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(displayApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labSexo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(displaySexo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labApellido)
                            .addComponent(labNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(displayApellido)
                            .addComponent(displayNombre)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labSexo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(displaySexo)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labTipoS)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labCiudad)
                            .addComponent(labFechaN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(displayCiudad)
                            .addComponent(displayFechaN)
                            .addComponent(displayTipoS))))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        labTipoD.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        labTipoD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labTipoD.setText("Tipo de Donación");

        cboxCentro.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        cboxCentro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CONCEPCIÓN", "TALCAHUANO", "CHIGUAYANTE" }));
        cboxCentro.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        cboxTipoDonacion.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        cboxTipoDonacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALTRUISTA", "REPOSICIÓN" }));
        cboxTipoDonacion.setActionCommand("CMD_TDBOX");
        cboxTipoDonacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cboxTipoDonacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxTipoDonacionActionPerformed(evt);
            }
        });

        labCentro.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        labCentro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labCentro.setText("Centro de Donación");

        labFechaD.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        labFechaD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labFechaD.setText("Fecha de Donación");

        labCodPaciente.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        labCodPaciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labCodPaciente.setText("Código de Paciente");

        jLayeredPane1.setLayer(labTipoD, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cboxCentro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtCodPaciente, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(cboxTipoDonacion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtFechaD, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(labCentro, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(labFechaD, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(labCodPaciente, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labFechaD, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFechaD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labCodPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodPaciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboxCentro, 0, 104, Short.MAX_VALUE)
                    .addComponent(labCentro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labTipoD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboxTipoDonacion, 0, 105, Short.MAX_VALUE))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(labFechaD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFechaD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labCentro)
                            .addComponent(labTipoD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboxCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labCodPaciente)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(cboxTipoDonacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labCodDonacion, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCodDonacion, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labBuscarRut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(txtBuscarRut, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarCodigoD, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarRut, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnIngresarD, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificarD, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarD, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodDonacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labCodDonacion)
                    .addComponent(btnBuscarCodigoD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarRut, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscarRut, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labBuscarRut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresarD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarD, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );

        jPanel1.getAccessibleContext().setAccessibleName("FICHA DE INGRESO DE DONACIÓN");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarDActionPerformed

    private void btnBuscarCodigoDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCodigoDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarCodigoDActionPerformed

    private void txtCodDonacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodDonacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodDonacionActionPerformed

    private void btnModificarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarDActionPerformed

    private void btnEliminarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarDActionPerformed

    private void cboxTipoDonacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxTipoDonacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxTipoDonacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDonacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDonacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDonacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDonacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDonacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscarCodigoD;
    public javax.swing.JButton btnBuscarRut;
    public javax.swing.JButton btnEliminarD;
    public javax.swing.JButton btnIngresarD;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JButton btnModificarD;
    public javax.swing.JComboBox<String> cboxCentro;
    public javax.swing.JComboBox<String> cboxTipoDonacion;
    public javax.swing.JLabel displayApellido;
    public javax.swing.JLabel displayCiudad;
    public javax.swing.JLabel displayFechaN;
    public javax.swing.JLabel displayNombre;
    public javax.swing.JLabel displaySexo;
    public javax.swing.JLabel displayTipoS;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labApellido;
    private javax.swing.JLabel labBuscarRut;
    private javax.swing.JLabel labCentro;
    private javax.swing.JLabel labCiudad;
    private javax.swing.JLabel labCodDonacion;
    private javax.swing.JLabel labCodPaciente;
    private javax.swing.JLabel labFechaD;
    private javax.swing.JLabel labFechaN;
    private javax.swing.JLabel labNombre;
    private javax.swing.JLabel labSexo;
    private javax.swing.JLabel labTipoD;
    private javax.swing.JLabel labTipoS;
    public javax.swing.JTextField txtBuscarRut;
    public javax.swing.JTextField txtCodDonacion;
    public javax.swing.JTextField txtCodPaciente;
    public javax.swing.JTextField txtFechaD;
    // End of variables declaration//GEN-END:variables
}
